// lib/marketplace/data.ts
//
// The seeded skill catalogue — the single source of truth for skills across
// the app. /marketplace browses it; /adoption derives its Skills tab from it
// (see library.ts). All figures are mock, and every `scan` is a *simulated*
// pre-share check: the UI labels it as such so nobody reads it as live DLP.
//
// The four skills that predate the marketplace (claims-summary, policy-qa,
// broker-reply, hr-screening) keep their original ids, names, purposes, teams,
// statuses and counts so the Adoption tab reads identically after migration.
//
// Status mix is deliberate: 11 approved (a browsable catalogue), 3 in review
// (an actionable queue), 2 blocked (refusals with reasons that show the gate
// has teeth).
import type { MarketplaceSkill } from './types'

const DAVY = 'Davy · Security & Compliance'

export const MARKETPLACE_SKILLS: MarketplaceSkill[] = [
  // ── Approved ─────────────────────────────────────────────────────────────
  {
    id: 'claims-summary',
    name: 'Claims file summariser',
    purpose: 'Turns a claims folder into a structured 1-page summary',
    whenToUse: [
      'Picking up a file someone else handled',
      'Preparing a hand-over or escalation note',
      'Before a reserving or settlement discussion',
    ],
    exampleInput: 'Summarise claim 2026-AN-4471 — cover, timeline, open questions, recommended next step.',
    category: 'claims',
    builder: 'Sofie Maes',
    sourceTeam: 'Claims · Antwerp',
    version: '2.1',
    submittedAt: '2026-02-11',
    status: 'approved',
    reviewer: DAVY,
    adopters: 96,
    reachable: 140,
    reuseTeams: 4,
    suggestedTeams: ['Legal', 'Motor claims · Ghent'],
    usesThisMonth: 620,
    minutesSavedPerUse: 22,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'No outbound calls — operates on pasted content only' },
        { kind: 'pii', severity: 'low', label: 'PII in prompt', detail: 'Claimant name and policy number, retained in-tenant', piiTypes: ['PERSON'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Guidewire ClaimCenter export (approved)' },
        { kind: 'framework', severity: 'ok', label: 'GDPR Art. 5', detail: 'Purpose-limited to claims handling; no secondary use', framework: 'gdpr' },
      ],
    },
    reviews: [
      { author: 'Tom Peeters', team: 'Claims · Ghent', rating: 5, comment: 'Cut my hand-over prep from 40 minutes to about five.', at: '2026-07-02' },
      { author: 'Anke Willems', team: 'Legal', rating: 4, comment: 'Great structure. Wish it flagged limitation dates explicitly.', at: '2026-07-19' },
      { author: 'Ruben De Smet', team: 'Motor claims · Ghent', rating: 5, comment: 'We adopted it team-wide in a week.', at: '2026-08-05' },
    ],
  },
  {
    id: 'policy-qa',
    name: 'Policy wording Q&A',
    purpose: 'Answers coverage questions against the policy library',
    whenToUse: [
      'Checking whether a specific loss is covered',
      'Comparing wording between two product versions',
      'Answering a broker question you would otherwise escalate',
    ],
    exampleInput: 'Under the 2025 commercial property wording, is flood damage to outdoor stock covered?',
    category: 'underwriting',
    builder: 'Marijke Claes',
    sourceTeam: 'Underwriting',
    version: '1.6',
    submittedAt: '2026-03-04',
    status: 'approved',
    reviewer: DAVY,
    adopters: 71,
    reachable: 120,
    reuseTeams: 3,
    suggestedTeams: ['Broker desk', 'Claims · Antwerp'],
    usesThisMonth: 480,
    minutesSavedPerUse: 12,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None — retrieval stays inside the policy library' },
        { kind: 'pii', severity: 'ok', label: 'PII in prompt', detail: 'Product wording only; no personal data' },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'SharePoint / Policy library (approved, read-only)' },
        { kind: 'framework', severity: 'low', label: 'EU AI Act Art. 50', detail: 'Advisory output — answers carry a "verify against wording" notice', framework: 'euAiAct' },
      ],
    },
    reviews: [
      { author: 'Hugo Janssens', team: 'Broker desk', rating: 5, comment: 'Cites the clause every time. That is what makes it trustworthy.', at: '2026-06-28' },
      { author: 'Lien Vermeulen', team: 'Underwriting', rating: 4, comment: 'Occasionally too literal on older wordings.', at: '2026-08-11' },
    ],
  },
  {
    id: 'fnol-triage',
    name: 'FNOL triage classifier',
    purpose: 'Sorts first notifications of loss by severity, complexity and route',
    whenToUse: [
      'Clearing the overnight notification queue',
      'Deciding fast-track vs. adjuster assignment',
      'Spotting a large-loss notification early',
    ],
    exampleInput: 'Classify this FNOL: water ingress, commercial kitchen, business interruption claimed, no injuries.',
    category: 'claims',
    builder: 'Sofie Maes',
    sourceTeam: 'Claims · Antwerp',
    version: '1.4',
    submittedAt: '2026-04-16',
    status: 'approved',
    reviewer: DAVY,
    adopters: 58,
    reachable: 110,
    reuseTeams: 3,
    suggestedTeams: ['Motor claims · Ghent', 'Customer service'],
    usesThisMonth: 900,
    minutesSavedPerUse: 6,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'No outbound calls' },
        { kind: 'pii', severity: 'low', label: 'PII in prompt', detail: 'Contact details from the notification form', piiTypes: ['PERSON', 'PHONE', 'ADDRESS'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Guidewire ClaimCenter (approved)' },
        { kind: 'framework', severity: 'low', label: 'EU AI Act Art. 14', detail: 'Routing suggestion only — an adjuster confirms every assignment', framework: 'euAiAct' },
      ],
    },
    reviews: [
      { author: 'Ruben De Smet', team: 'Motor claims · Ghent', rating: 4, comment: 'Reliable on the routine 80%. We still eyeball the large losses.', at: '2026-07-30' },
      { author: 'Nadia Boulahia', team: 'Customer service', rating: 4, comment: 'Queue is clear by 9am now.', at: '2026-08-14' },
    ],
  },
  {
    id: 'subrogation-scan',
    name: 'Subrogation opportunity scan',
    purpose: 'Reads a settled claim and flags recovery angles worth pursuing',
    whenToUse: [
      'Reviewing settled claims above the recovery threshold',
      'Quarterly recovery sweeps over a closed portfolio',
    ],
    exampleInput: 'Scan this settled motor claim for third-party recovery potential and name the evidence needed.',
    category: 'claims',
    builder: 'Ruben De Smet',
    sourceTeam: 'Claims · Ghent',
    version: '1.2',
    submittedAt: '2026-05-02',
    status: 'approved',
    reviewer: DAVY,
    adopters: 34,
    reachable: 70,
    reuseTeams: 2,
    suggestedTeams: ['Legal', 'Claims · Antwerp'],
    usesThisMonth: 210,
    minutesSavedPerUse: 25,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'low', label: 'PII in prompt', detail: 'Third-party names and vehicle registrations', piiTypes: ['PERSON'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Guidewire ClaimCenter (approved)' },
        { kind: 'framework', severity: 'ok', label: 'GDPR Art. 6', detail: 'Legitimate interest — recovery of paid claims, documented', framework: 'gdpr' },
      ],
    },
    reviews: [
      { author: 'Anke Willems', team: 'Legal', rating: 5, comment: 'Found two recoveries in the first week that we had written off.', at: '2026-06-20' },
    ],
  },
  {
    id: 'complaint-response',
    name: 'Complaint response drafter',
    purpose: 'Drafts a regulator-ready complaint response in house tone',
    whenToUse: [
      'Responding to a formal complaint within the statutory window',
      'Preparing an Ombudsman submission',
      'Rewriting a rejection so it is clear and defensible',
    ],
    exampleInput: 'Draft a response to this complaint about a declined subsidence claim. Acknowledge, explain the wording, offer the escalation route.',
    category: 'customer-service',
    builder: 'Nadia Boulahia',
    sourceTeam: 'Customer service',
    version: '2.0',
    submittedAt: '2026-03-27',
    status: 'approved',
    reviewer: DAVY,
    adopters: 47,
    reachable: 85,
    reuseTeams: 3,
    suggestedTeams: ['Claims · Antwerp', 'Legal'],
    usesThisMonth: 410,
    minutesSavedPerUse: 14,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'medium', label: 'PII in prompt', detail: 'Complainant name, address and email pasted in full', piiTypes: ['PERSON', 'ADDRESS', 'EMAIL'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Complaints register (approved)' },
        { kind: 'framework', severity: 'ok', label: 'EIOPA', detail: 'Complaint-handling response times and content requirements met', framework: 'eiopa' },
      ],
    },
    reviews: [
      { author: 'Anke Willems', team: 'Legal', rating: 4, comment: 'Tone is right. Always check the statutory deadlines it quotes.', at: '2026-07-08' },
      { author: 'Sofie Maes', team: 'Claims · Antwerp', rating: 5, comment: 'The hardest letters are now a 10-minute job.', at: '2026-08-02' },
    ],
  },
  {
    id: 'sanctions-note',
    name: 'Sanctions screening note writer',
    purpose: 'Writes the decision note behind a sanctions or PEP screening hit',
    whenToUse: [
      'Documenting why a screening hit was cleared or escalated',
      'Preparing evidence for a compliance audit',
    ],
    exampleInput: 'Write the decision note for this partial name match against the EU consolidated list — cleared on date of birth mismatch.',
    category: 'legal',
    builder: 'Anke Willems',
    sourceTeam: 'Legal',
    version: '1.1',
    submittedAt: '2026-04-30',
    status: 'approved',
    reviewer: DAVY,
    adopters: 22,
    reachable: 45,
    reuseTeams: 2,
    suggestedTeams: ['Underwriting', 'Claims · Antwerp'],
    usesThisMonth: 340,
    minutesSavedPerUse: 9,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None — the sanctions list is loaded in-tenant' },
        { kind: 'pii', severity: 'medium', label: 'PII in prompt', detail: 'Name and date of birth of the screened party', piiTypes: ['PERSON'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Screening case file (approved)' },
        { kind: 'framework', severity: 'low', label: 'GDPR Art. 22', detail: 'Human writes and signs the decision; the skill drafts only', framework: 'gdpr' },
      ],
    },
    reviews: [
      { author: 'Marijke Claes', team: 'Underwriting', rating: 5, comment: 'Audit trail quality went up, not just speed.', at: '2026-08-09' },
    ],
  },
  {
    id: 'tender-summary',
    name: 'Broker tender summariser',
    purpose: 'Condenses a broker tender pack into risk, exposure and decision points',
    whenToUse: [
      'Screening an inbound tender before assigning an underwriter',
      'Preparing the underwriting committee pack',
    ],
    exampleInput: 'Summarise this 60-page tender: exposures, claims history, capacity asked, and the three questions we should ask back.',
    category: 'distribution',
    builder: 'Hugo Janssens',
    sourceTeam: 'Broker desk',
    version: '1.3',
    submittedAt: '2026-02-25',
    status: 'approved',
    reviewer: DAVY,
    adopters: 29,
    reachable: 55,
    reuseTeams: 2,
    suggestedTeams: ['Underwriting', 'Distribution · Ghent'],
    usesThisMonth: 130,
    minutesSavedPerUse: 30,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'ok', label: 'PII in prompt', detail: 'Corporate data only' },
        { kind: 'dataStore', severity: 'low', label: 'Data store', detail: 'Broker tender mailbox — commercially sensitive, in-tenant' },
        { kind: 'framework', severity: 'ok', label: 'ISO 42001', detail: 'Registered use case with a named owner', framework: 'iso42001' },
      ],
    },
    reviews: [
      { author: 'Marijke Claes', team: 'Underwriting', rating: 5, comment: 'We screen twice the tenders with the same desk.', at: '2026-07-15' },
      { author: 'Wim Coppens', team: 'Distribution · Ghent', rating: 4, comment: 'Struggles with scanned appendices.', at: '2026-08-18' },
    ],
  },
  {
    id: 'treaty-diff',
    name: 'Reinsurance treaty diff',
    purpose: 'Compares two treaty wordings and explains what materially changed',
    whenToUse: [
      'Reviewing a renewal against the expiring treaty',
      'Checking a reinsurer counter-draft before signing',
    ],
    exampleInput: 'Compare the 2026 quota-share draft against the 2025 treaty. What changed in exclusions and reinstatement terms?',
    category: 'underwriting',
    builder: 'Marijke Claes',
    sourceTeam: 'Underwriting',
    version: '1.0',
    submittedAt: '2026-05-19',
    status: 'approved',
    reviewer: DAVY,
    adopters: 11,
    reachable: 18,
    reuseTeams: 1,
    suggestedTeams: ['Legal', 'Finance'],
    usesThisMonth: 60,
    minutesSavedPerUse: 45,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'ok', label: 'PII in prompt', detail: 'Contract text only' },
        { kind: 'dataStore', severity: 'low', label: 'Data store', detail: 'Treaty repository — restricted, in-tenant' },
        { kind: 'framework', severity: 'ok', label: 'ISO 42001', detail: 'Registered; output reviewed by the treaty owner', framework: 'iso42001' },
      ],
    },
    reviews: [
      { author: 'Bart Nys', team: 'Finance', rating: 5, comment: 'Caught a reinstatement change three of us had read past.', at: '2026-08-21' },
    ],
  },
  {
    id: 'reserving-commentary',
    name: 'Reserving commentary drafter',
    purpose: 'Drafts the narrative behind a reserving movement from the triangles',
    whenToUse: [
      'Quarter-end reserving pack',
      'Explaining a material movement to the audit committee',
    ],
    exampleInput: 'Draft commentary for the Q2 motor bodily-injury movement: +4.2m, driven by two large losses and a claims-inflation reassessment.',
    category: 'finance',
    builder: 'Bart Nys',
    sourceTeam: 'Finance',
    version: '1.2',
    submittedAt: '2026-03-12',
    status: 'approved',
    reviewer: DAVY,
    adopters: 14,
    reachable: 22,
    reuseTeams: 1,
    suggestedTeams: ['Underwriting'],
    usesThisMonth: 75,
    minutesSavedPerUse: 35,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'ok', label: 'PII in prompt', detail: 'Aggregated figures only' },
        { kind: 'dataStore', severity: 'low', label: 'Data store', detail: 'Actuarial reserving workspace — restricted, pre-announcement figures' },
        { kind: 'framework', severity: 'low', label: 'EIOPA', detail: 'Draft only; the signing actuary owns the final narrative', framework: 'eiopa' },
      ],
    },
    reviews: [
      { author: 'Marijke Claes', team: 'Underwriting', rating: 4, comment: 'Good first draft. Numbers always get re-checked by hand.', at: '2026-07-24' },
    ],
  },
  {
    id: 'incident-postmortem',
    name: 'Incident post-mortem writer',
    purpose: 'Turns an incident timeline and chat log into a blameless post-mortem',
    whenToUse: [
      'Within 48 hours of a P1 or P2 incident',
      'Preparing the monthly reliability review',
    ],
    exampleInput: 'Write a blameless post-mortem from this incident channel export: impact, timeline, contributing factors, actions with owners.',
    category: 'it',
    builder: 'Joris Vandenberghe',
    sourceTeam: 'IT Operations',
    version: '1.5',
    submittedAt: '2026-01-29',
    status: 'approved',
    reviewer: DAVY,
    adopters: 26,
    reachable: 40,
    reuseTeams: 2,
    suggestedTeams: ['IT Security'],
    usesThisMonth: 45,
    minutesSavedPerUse: 40,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'low', label: 'PII in prompt', detail: 'Staff names in the chat export', piiTypes: ['PERSON', 'EMAIL'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'Incident channel export (approved)' },
        { kind: 'framework', severity: 'ok', label: 'ISO 42001', detail: 'Internal operations use case; low risk classification', framework: 'iso42001' },
      ],
    },
    reviews: [
      { author: 'Els Vanhoof', team: 'IT Security', rating: 5, comment: 'Post-mortems actually get written now.', at: '2026-06-11' },
      { author: 'Joris Vandenberghe', team: 'IT Operations', rating: 5, comment: 'The blameless framing holds up better than mine did.', at: '2026-07-01' },
    ],
  },
  {
    id: 'meeting-actions',
    name: 'Meeting action extractor',
    purpose: 'Pulls decisions, actions and owners out of meeting notes',
    whenToUse: [
      'After any meeting where actions were agreed verbally',
      'Turning a rambling transcript into a follow-up mail',
    ],
    exampleInput: 'Extract decisions, actions and owners from these notes. Flag anything agreed without a named owner.',
    category: 'it',
    builder: 'Els Vanhoof',
    sourceTeam: 'IT Security',
    version: '3.0',
    submittedAt: '2026-01-15',
    status: 'approved',
    reviewer: DAVY,
    adopters: 188,
    reachable: 420,
    reuseTeams: 9,
    suggestedTeams: ['Claims · Antwerp', 'Finance', 'Distribution · Ghent'],
    usesThisMonth: 1100,
    minutesSavedPerUse: 5,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'low', label: 'PII in prompt', detail: 'Attendee names', piiTypes: ['PERSON'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'None — operates on pasted notes' },
        { kind: 'framework', severity: 'ok', label: 'GDPR Art. 5', detail: 'No storage; nothing retained beyond the session', framework: 'gdpr' },
      ],
    },
    reviews: [
      { author: 'Bart Nys', team: 'Finance', rating: 5, comment: 'The most-used thing we have. Boring and perfect.', at: '2026-05-30' },
      { author: 'Wim Coppens', team: 'Distribution · Ghent', rating: 4, comment: 'Sometimes invents an owner. Always check that column.', at: '2026-07-22' },
      { author: 'Nadia Boulahia', team: 'Customer service', rating: 5, comment: 'Saves me ten minutes after every single call.', at: '2026-08-16' },
    ],
  },

  // ── In review ────────────────────────────────────────────────────────────
  {
    id: 'broker-reply',
    name: 'Broker reply drafter',
    purpose: 'Drafts broker correspondence in house tone',
    whenToUse: [
      'Replying to routine broker queries at volume',
      'Keeping tone consistent across a distributed desk',
    ],
    exampleInput: 'Draft a reply to this broker asking why the renewal premium moved 12%. Explain, keep it warm, offer a call.',
    category: 'distribution',
    builder: 'Wim Coppens',
    sourceTeam: 'Distribution · Ghent',
    version: '0.9',
    submittedAt: '2026-08-06',
    status: 'in_review',
    reviewer: DAVY,
    note: 'Pending DLP check — pulls from broker CRM export',
    adopters: 12,
    reachable: 90,
    reuseTeams: 1,
    suggestedTeams: ['Distribution · Antwerp', 'Customer service'],
    usesThisMonth: 95,
    minutesSavedPerUse: 11,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'high', label: 'External egress', detail: 'crm.brokerportal.eu — not on the allowlist' },
        { kind: 'pii', severity: 'medium', label: 'PII in prompt', detail: 'Broker contact name, email and policy numbers', piiTypes: ['PERSON', 'EMAIL'] },
        { kind: 'dataStore', severity: 'ok', label: 'Data store', detail: 'SharePoint / Broker correspondence (approved)' },
        { kind: 'framework', severity: 'medium', label: 'GDPR Art. 28', detail: 'External processor not on the register — no DPA on file', framework: 'gdpr' },
      ],
    },
    reviews: [],
  },
  {
    id: 'fraud-signals',
    name: 'Fraud signal highlighter',
    purpose: 'Highlights inconsistencies in a claim narrative worth a second look',
    whenToUse: [
      'Screening claims above the referral threshold',
      'Preparing a referral pack for the fraud team',
    ],
    exampleInput: 'Read this claim narrative and statement. List inconsistencies and what evidence would resolve each.',
    category: 'claims',
    builder: 'Tom Peeters',
    sourceTeam: 'Claims · Ghent',
    version: '0.4',
    submittedAt: '2026-08-13',
    status: 'in_review',
    reviewer: DAVY,
    note: 'Awaiting decision — profiling risk if the score reaches the adjuster before a human read',
    adopters: 6,
    reachable: 75,
    reuseTeams: 0,
    suggestedTeams: ['Claims · Antwerp'],
    usesThisMonth: 40,
    minutesSavedPerUse: 18,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'high', label: 'PII in prompt', detail: 'Full claimant statement including address and bank details', piiTypes: ['PERSON', 'ADDRESS', 'CREDIT_CARD'] },
        { kind: 'dataStore', severity: 'medium', label: 'Data store', detail: 'Writes a score back to the claim record — creates a profiling artefact' },
        { kind: 'framework', severity: 'high', label: 'EU AI Act Art. 6', detail: 'Insurance fraud scoring may fall in the high-risk annex — classification needed', framework: 'euAiAct' },
      ],
    },
    reviews: [],
  },
  {
    id: 'pricing-benchmark',
    name: 'Pricing benchmark researcher',
    purpose: 'Gathers public market pricing signals for a product line',
    whenToUse: [
      'Preparing a rate review',
      'Sense-checking a proposed rate change against the market',
    ],
    exampleInput: 'Summarise publicly available pricing and coverage trends for Belgian commercial fleet motor in the last two quarters.',
    category: 'underwriting',
    builder: 'Hugo Janssens',
    sourceTeam: 'Broker desk',
    version: '0.6',
    submittedAt: '2026-08-20',
    status: 'in_review',
    reviewer: DAVY,
    note: 'Awaiting decision — uses an unvetted web search connector',
    adopters: 4,
    reachable: 30,
    reuseTeams: 0,
    suggestedTeams: ['Underwriting', 'Finance'],
    usesThisMonth: 25,
    minutesSavedPerUse: 28,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'high', label: 'External egress', detail: 'serpapi.com — unvetted third-party search connector' },
        { kind: 'pii', severity: 'ok', label: 'PII in prompt', detail: 'Market data only' },
        { kind: 'dataStore', severity: 'medium', label: 'Data store', detail: 'Sends internal rate assumptions outbound as query context' },
        { kind: 'framework', severity: 'medium', label: 'GDPR Art. 44', detail: 'Connector processes outside the EEA — transfer basis unconfirmed', framework: 'gdpr' },
      ],
    },
    reviews: [],
  },

  // ── Blocked ──────────────────────────────────────────────────────────────
  {
    id: 'hr-screening',
    name: 'CV screening assistant',
    purpose: 'Ranks candidates against a role brief',
    whenToUse: ['Shortlisting for a high-volume role'],
    exampleInput: 'Rank these 40 CVs against the claims handler role brief and explain the top five.',
    category: 'hr',
    builder: 'Katrien Dupont',
    sourceTeam: 'HR',
    version: '0.3',
    submittedAt: '2026-06-18',
    status: 'blocked',
    reviewer: DAVY,
    note: 'Blocked — automated profiling of candidates (GDPR Art. 22)',
    adopters: 3,
    reachable: 20,
    reuseTeams: 0,
    suggestedTeams: [],
    usesThisMonth: 0,
    minutesSavedPerUse: 20,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'high', label: 'PII in prompt', detail: 'Full candidate CVs — name, address, date of birth, history', piiTypes: ['PERSON', 'ADDRESS', 'EMAIL', 'PHONE'] },
        { kind: 'dataStore', severity: 'medium', label: 'Data store', detail: 'Recruitment ATS — candidate records outside the retention policy' },
        { kind: 'framework', severity: 'high', label: 'GDPR Art. 22', detail: 'Ranking materially affects a hiring decision — automated profiling', framework: 'gdpr' },
        { kind: 'framework', severity: 'high', label: 'EU AI Act Annex III', detail: 'Employment screening is a listed high-risk use', framework: 'euAiAct' },
      ],
    },
    reviews: [],
  },
  {
    id: 'medical-severity',
    name: 'Medical report severity scorer',
    purpose: 'Scores injury severity from a medical report to size a bodily-injury reserve',
    whenToUse: ['Setting an initial reserve on a bodily-injury claim'],
    exampleInput: 'From this medical report, score injury severity and suggest a reserve band.',
    category: 'claims',
    builder: 'Tom Peeters',
    sourceTeam: 'Claims · Ghent',
    version: '0.2',
    submittedAt: '2026-07-09',
    status: 'blocked',
    reviewer: DAVY,
    note: 'Blocked — special-category health data with no lawful basis for this processing (GDPR Art. 9)',
    adopters: 2,
    reachable: 35,
    reuseTeams: 0,
    suggestedTeams: [],
    usesThisMonth: 0,
    minutesSavedPerUse: 30,
    scan: {
      scannedAt: '2026-08-24',
      findings: [
        { kind: 'egress', severity: 'ok', label: 'External egress', detail: 'None' },
        { kind: 'pii', severity: 'high', label: 'PII in prompt', detail: 'Medical reports — special-category health data', piiTypes: ['PERSON', 'ADDRESS'] },
        { kind: 'dataStore', severity: 'high', label: 'Data store', detail: 'Medical annexes copied into a general claims workspace' },
        { kind: 'framework', severity: 'high', label: 'GDPR Art. 9', detail: 'Special-category processing without an identified lawful basis', framework: 'gdpr' },
      ],
    },
    reviews: [],
  },
]

/**
 * Average Q1 score lift attributed to each builder's approved skills. Seeded
 * per person rather than derived — a lift figure comes from the transcript
 * pipeline (see QUALITY_PIPELINE), not from anything in this file.
 */
export const BUILDER_SCORE_LIFT: Record<string, number> = {
  'Sofie Maes': 14,
  'Marijke Claes': 12,
  'Els Vanhoof': 11,
  'Nadia Boulahia': 9,
  'Anke Willems': 9,
  'Hugo Janssens': 8,
  'Ruben De Smet': 8,
  'Joris Vandenberghe': 7,
  'Bart Nys': 6,
  'Wim Coppens': 5,
  'Tom Peeters': 5,
  'Katrien Dupont': 3,
}
