// AI Visibility Page Data

export const aiModelsInventory = [
  {
    id: "model-1",
    name: "Claims Assessment AI",
    provider: "Internal (Azure OpenAI)",
    version: "v2.4.1",
    type: "Large Language Model",
    status: "production",
    lastUpdated: "2024-11-15",
    dataInputs: ["Claims forms", "Medical records", "Policy documents"],
    dataOutputs: ["Risk assessment", "Claim decision", "Fraud score"],
    promptTemplates: 12,
    monthlyInferences: 45200,
    latencyP95: "1.2s",
    costPerMonth: "NOK 78,500",
    complianceStatus: "compliant",
  },
  {
    id: "model-2",
    name: "Kundeservice Chatbot",
    provider: "Anthropic (Claude)",
    version: "claude-3-sonnet",
    type: "Conversational AI",
    status: "production",
    lastUpdated: "2024-10-22",
    dataInputs: ["Customer queries", "Policy data", "Account history"],
    dataOutputs: ["Response text", "Action triggers", "Sentiment score"],
    promptTemplates: 24,
    monthlyInferences: 156000,
    latencyP95: "0.8s",
    costPerMonth: "NOK 124,200",
    complianceStatus: "compliant",
  },
  {
    id: "model-3",
    name: "Underwriting Risk Engine",
    provider: "Internal (Custom ML)",
    version: "v3.1.0",
    type: "Risk Scoring Model",
    status: "production",
    lastUpdated: "2024-11-01",
    dataInputs: ["Application data", "Health records", "Financial history"],
    dataOutputs: ["Risk score", "Premium calculation", "Exclusions"],
    promptTemplates: 0,
    monthlyInferences: 8520,
    latencyP95: "2.4s",
    costPerMonth: "NOK 45,800",
    complianceStatus: "review-needed",
  },
  {
    id: "model-4",
    name: "Fraud Detection System",
    provider: "Internal (TensorFlow)",
    version: "v1.8.3",
    type: "Anomaly Detection",
    status: "production",
    lastUpdated: "2024-09-30",
    dataInputs: ["Transaction patterns", "Claims history", "Behavioral data"],
    dataOutputs: ["Fraud probability", "Alert triggers", "Investigation queue"],
    promptTemplates: 0,
    monthlyInferences: 34000,
    latencyP95: "0.3s",
    costPerMonth: "NOK 32,100",
    complianceStatus: "compliant",
  },
  {
    id: "model-5",
    name: "Document Processing AI",
    provider: "Google (Document AI)",
    version: "v1.2",
    type: "Document Understanding",
    status: "production",
    lastUpdated: "2024-11-08",
    dataInputs: ["Scanned documents", "PDFs", "Images"],
    dataOutputs: ["Extracted text", "Entity recognition", "Classification"],
    promptTemplates: 8,
    monthlyInferences: 28400,
    latencyP95: "3.1s",
    costPerMonth: "NOK 56,300",
    complianceStatus: "compliant",
  },
]

export const dataSourcesInventory = [
  {
    id: "data-1",
    name: "Customer CRM Database",
    type: "Relational Database",
    classification: "confidential",
    location: "Azure Norway East",
    recordCount: "2.4M customers",
    refreshFrequency: "Real-time",
    retentionPeriod: "7 years",
    encryptionStatus: "AES-256 at rest, TLS 1.3 in transit",
    accessControls: "RBAC with MFA",
    gdprCompliant: true,
    connectedModels: ["model-2", "model-5"],
    lastAudit: "2024-10-15",
    dataOwner: "Customer Operations",
  },
  {
    id: "data-2",
    name: "Claims Processing System",
    type: "Document Store",
    classification: "restricted",
    location: "Azure Norway East",
    recordCount: "8.7M claims",
    refreshFrequency: "Real-time",
    retentionPeriod: "10 years",
    encryptionStatus: "AES-256 at rest, TLS 1.3 in transit",
    accessControls: "RBAC with MFA + IP whitelist",
    gdprCompliant: true,
    connectedModels: ["model-1", "model-4"],
    lastAudit: "2024-11-01",
    dataOwner: "Claims Department",
  },
  {
    id: "data-3",
    name: "Health Records Vault",
    type: "Encrypted Data Lake",
    classification: "restricted",
    location: "Azure Norway East (Isolated)",
    recordCount: "1.2M records",
    refreshFrequency: "Daily batch",
    retentionPeriod: "15 years",
    encryptionStatus: "AES-256 + HSM key management",
    accessControls: "Zero-trust + biometric",
    gdprCompliant: true,
    connectedModels: ["model-1", "model-3"],
    lastAudit: "2024-11-20",
    dataOwner: "Medical Underwriting",
  },
  {
    id: "data-4",
    name: "Actuarial Data Warehouse",
    type: "Analytics Database",
    classification: "confidential",
    location: "Azure Norway East",
    recordCount: "15 years historical",
    refreshFrequency: "Weekly",
    retentionPeriod: "Indefinite",
    encryptionStatus: "AES-256 at rest",
    accessControls: "RBAC + data masking",
    gdprCompliant: true,
    connectedModels: ["model-3", "model-4"],
    lastAudit: "2024-09-30",
    dataOwner: "Risk Analytics",
  },
  {
    id: "data-5",
    name: "External Market Data Feed",
    type: "API Integration",
    classification: "internal",
    location: "Third-party (Bloomberg)",
    recordCount: "Real-time feeds",
    refreshFrequency: "Continuous",
    retentionPeriod: "90 days",
    encryptionStatus: "TLS 1.3 in transit",
    accessControls: "API key + IP whitelist",
    gdprCompliant: true,
    connectedModels: [],
    lastAudit: "2024-10-01",
    dataOwner: "Investment Team",
  },
]

export const promptsInventory = [
  {
    id: "prompt-1",
    name: "Claims Initial Assessment",
    model: "Claims Assessment AI",
    category: "Decision Support",
    version: "v3.2",
    lastModified: "2024-11-10",
    status: "approved",
    riskLevel: "high",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Required for >NOK 100k",
    avgTokens: 2400,
    description: "Evaluates claims against policy terms.",
  },
  {
    id: "prompt-2",
    name: "Customer Query Response",
    model: "Kundeservice Chatbot",
    category: "Customer Service",
    version: "v5.1",
    lastModified: "2024-11-18",
    status: "approved",
    riskLevel: "medium",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Escalation triggers",
    avgTokens: 850,
    description: "Handles customer inquiries in Norwegian/English.",
  },
  {
    id: "prompt-3",
    name: "Policy Terms Explanation",
    model: "Kundeservice Chatbot",
    category: "Information",
    version: "v2.8",
    lastModified: "2024-10-25",
    status: "approved",
    riskLevel: "low",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Not required",
    avgTokens: 1200,
    description: "Explains policy terms in plain language.",
  },
  {
    id: "prompt-4",
    name: "Fraud Pattern Analysis",
    model: "Claims Assessment AI",
    category: "Risk Detection",
    version: "v1.4",
    lastModified: "2024-09-15",
    status: "approved",
    riskLevel: "high",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Always required",
    avgTokens: 3200,
    description: "Analyses claims for fraud indicators.",
  },
  {
    id: "prompt-5",
    name: "Document Classification",
    model: "Document Processing AI",
    category: "Automation",
    version: "v2.0",
    lastModified: "2024-11-05",
    status: "approved",
    riskLevel: "low",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Sampling only",
    avgTokens: 600,
    description: "Classifies and routes documents.",
  },
  {
    id: "prompt-6",
    name: "Underwriting Summary",
    model: "Claims Assessment AI",
    category: "Decision Support",
    version: "v1.9",
    lastModified: "2024-10-30",
    status: "under-review",
    riskLevel: "high",
    injectionProtection: true,
    outputValidation: true,
    humanReview: "Always required",
    avgTokens: 2800,
    description: "Generates underwriting summaries.",
  },
]

export const infrastructureInventory = [
  {
    id: "infra-1",
    name: "Azure OpenAI Service",
    type: "AI Platform",
    provider: "Microsoft Azure",
    region: "Norway East",
    status: "healthy",
    uptime: 99.97,
    lastIncident: "2024-08-12",
    securityCertifications: ["ISO 27001", "SOC 2", "GDPR"],
    networkIsolation: "Private endpoints",
    costPerMonth: "NOK 245,000",
    connectedModels: ["model-1", "model-2"],
    scalingPolicy: "Auto-scale 2-10 instances",
    backupStrategy: "Multi-region failover",
  },
  {
    id: "infra-2",
    name: "ML Training Cluster",
    type: "Compute Cluster",
    provider: "Microsoft Azure",
    region: "Norway East",
    status: "healthy",
    uptime: 99.89,
    lastIncident: "2024-10-03",
    securityCertifications: ["ISO 27001", "SOC 2"],
    networkIsolation: "VNet isolated",
    costPerMonth: "NOK 128,000",
    connectedModels: ["model-3", "model-4"],
    scalingPolicy: "On-demand GPU allocation",
    backupStrategy: "Model checkpointing",
  },
  {
    id: "infra-3",
    name: "Inference API Gateway",
    type: "API Management",
    provider: "Microsoft Azure",
    region: "Norway East + West Europe",
    status: "healthy",
    uptime: 99.99,
    lastIncident: "2024-05-22",
    securityCertifications: ["ISO 27001", "PCI DSS"],
    networkIsolation: "WAF protected",
    costPerMonth: "NOK 34,500",
    connectedModels: ["model-1", "model-2", "model-3", "model-4", "model-5"],
    scalingPolicy: "Global load balancing",
    backupStrategy: "Active-active failover",
  },
  {
    id: "infra-4",
    name: "Model Registry",
    type: "MLOps Platform",
    provider: "Azure ML",
    region: "Norway East",
    status: "healthy",
    uptime: 99.95,
    lastIncident: "2024-09-18",
    securityCertifications: ["ISO 27001"],
    networkIsolation: "Private endpoints",
    costPerMonth: "NOK 12,800",
    connectedModels: ["model-1", "model-2", "model-3", "model-4", "model-5"],
    scalingPolicy: "N/A",
    backupStrategy: "Geo-redundant storage",
  },
  {
    id: "infra-5",
    name: "Logging & Monitoring",
    type: "Observability",
    provider: "Azure Monitor + Datadog",
    region: "Norway East",
    status: "healthy",
    uptime: 99.98,
    lastIncident: "2024-07-09",
    securityCertifications: ["SOC 2", "GDPR"],
    networkIsolation: "Secure log forwarding",
    costPerMonth: "NOK 45,200",
    connectedModels: ["model-1", "model-2", "model-3", "model-4", "model-5"],
    scalingPolicy: "Auto-retention policies",
    backupStrategy: "90-day retention",
  },
]

export const vendorAIInventory = [
  {
    id: "vendor-1",
    name: "Anthropic",
    service: "Claude API",
    contractStatus: "active",
    contractExpiry: "2025-12-31",
    annualSpend: "NOK 1,490,400",
    slaUptime: 99.9,
    actualUptime: 99.94,
    dataProcessingLocation: "EU (Ireland)",
    gdprDpa: true,
    aiActCompliant: true,
    securityAudit: "2024-09-15",
    riskRating: "low",
    primaryContact: "enterprise@anthropic.com",
    useCases: ["Chatbot", "Summarisation"],
    exitStrategy: "Azure OpenAI fallback",
  },
  {
    id: "vendor-2",
    name: "Google Cloud",
    service: "Document AI + Vertex AI",
    contractStatus: "active",
    contractExpiry: "2025-06-30",
    annualSpend: "NOK 675,600",
    slaUptime: 99.95,
    actualUptime: 99.97,
    dataProcessingLocation: "EU (Finland)",
    gdprDpa: true,
    aiActCompliant: true,
    securityAudit: "2024-10-01",
    riskRating: "low",
    primaryContact: "cloud-support@google.com",
    useCases: ["Document processing", "OCR"],
    exitStrategy: "Azure Form Recognizer",
  },
  {
    id: "vendor-3",
    name: "Microsoft Azure",
    service: "Azure OpenAI + Azure ML",
    contractStatus: "active",
    contractExpiry: "2026-03-31",
    annualSpend: "NOK 4,476,000",
    slaUptime: 99.9,
    actualUptime: 99.87,
    dataProcessingLocation: "Norway East",
    gdprDpa: true,
    aiActCompliant: true,
    securityAudit: "2024-11-01",
    riskRating: "low",
    primaryContact: "azure-enterprise@microsoft.com",
    useCases: ["Claims AI", "Training", "Hosting"],
    exitStrategy: "Multi-cloud strategy",
  },
  {
    id: "vendor-4",
    name: "Datadog",
    service: "AI Observability",
    contractStatus: "active",
    contractExpiry: "2025-09-30",
    annualSpend: "NOK 542,400",
    slaUptime: 99.9,
    actualUptime: 99.96,
    dataProcessingLocation: "EU (Germany)",
    gdprDpa: true,
    aiActCompliant: true,
    securityAudit: "2024-08-20",
    riskRating: "low",
    primaryContact: "enterprise@datadoghq.com",
    useCases: ["Monitoring", "Performance"],
    exitStrategy: "Azure Monitor backup",
  },
  {
    id: "vendor-5",
    name: "Weights & Biases",
    service: "MLOps Platform",
    contractStatus: "evaluation",
    contractExpiry: "2025-03-31",
    annualSpend: "NOK 180,000",
    slaUptime: 99.5,
    actualUptime: 99.82,
    dataProcessingLocation: "EU (Ireland)",
    gdprDpa: true,
    aiActCompliant: "pending" as const,
    securityAudit: "2024-11-15",
    riskRating: "medium",
    primaryContact: "sales@wandb.com",
    useCases: ["Experiment tracking", "Versioning"],
    exitStrategy: "Azure ML native",
  },
]

// Calculate visibility summary
export const getVisibilitySummary = () => ({
  totalModels: aiModelsInventory.length,
  totalDataSources: dataSourcesInventory.length,
  totalPrompts: promptsInventory.length,
  totalInfrastructure: infrastructureInventory.length,
  totalVendors: vendorAIInventory.length,
  modelsInProduction: aiModelsInventory.filter((m) => m.status === "production").length,
  promptsApproved: promptsInventory.filter((p) => p.status === "approved").length,
  vendorsCompliant: vendorAIInventory.filter((v) => v.aiActCompliant === true).length,
  totalMonthlyInferences: aiModelsInventory.reduce((sum, m) => sum + m.monthlyInferences, 0),
  totalMonthlyCost: "NOK 2.1M",
  dataClassificationBreakdown: {
    restricted: dataSourcesInventory.filter((d) => d.classification === "restricted").length,
    confidential: dataSourcesInventory.filter((d) => d.classification === "confidential").length,
    internal: dataSourcesInventory.filter((d) => d.classification === "internal").length,
  },
})
