// Simulated data for AI-SPM and AI Asset Management

export type DeploymentStatus = "Active" | "Shadow" | "Deprecated" | "Testing"
export type ComplianceStatus = "Compliant" | "Partial" | "Non-compliant"
export type IncidentSeverity = "Low" | "Medium" | "High" | "Critical"
export type IncidentStatus = "Open" | "In progress" | "Resolved"
export type IncidentType = "Prompt injection" | "Data exfiltration" | "Model abuse" | "Policy violation"

// AI-SPM Dataset
export interface AISPMAsset {
  assetId: string
  modelName: string
  owner: string
  department: string
  hostingLocation: "Azure" | "AWS" | "GCP" | "On-premise"
  modelType: "LLM" | "CV model" | "Fine-tuned model" | "Agent"
  thirdParty: boolean
  sensitiveDataTypes: ("PII" | "PHI" | "IP" | "Financial" | "None")[]
  dataLineageScore: number
  likelihoodOfLeakage: number
  misconfigurationCount: number
  highRiskVulnerabilities: number
  dependencyCves: string[]
  promptInjectionAttemptsLast30Days: number
  dataExfiltrationAlertsLast30Days: number
  userRiskScore: number
  gdprStatus: ComplianceStatus
  euAiActStatus: ComplianceStatus
  nistAiRmfStatus: ComplianceStatus
  policyViolationsLast30Days: number
  riskScore: number
}

export interface SecurityIncident {
  incidentId: string
  date: string
  assetId: string
  type: IncidentType
  severity: IncidentSeverity
  status: IncidentStatus
  mttrHours: number
  description: string
}

// AI Asset Management Dataset
export interface AIAsset {
  assetId: string
  modelName: string
  version: string
  architecture: string
  owner: string
  department: string
  creationDate: string
  lastUpdated: string
  dependencyLibraries: string[]
  deploymentStatus: DeploymentStatus
  averageLatencyMs: number
  throughputQps: number
  modelAccuracy: number
  driftScore: number
  costPer1kTokens: number
  gpuHoursMonth: number
  cloudCostEstimateMonth: number
  datasetSizeGb: number
  callsLast30Days: number
  topUseCases: string[]
  businessUnits: string[]
  mostActiveUsers: string[]
}

// Generate AI-SPM Assets
export const aiSpmAssets: AISPMAsset[] = [
  {
    assetId: "spm-001",
    modelName: "CustomerServiceGPT",
    owner: "Sarah Mitchell",
    department: "Customer Support",
    hostingLocation: "Azure",
    modelType: "LLM",
    thirdParty: false,
    sensitiveDataTypes: ["PII", "Financial"],
    dataLineageScore: 85,
    likelihoodOfLeakage: 0.23,
    misconfigurationCount: 2,
    highRiskVulnerabilities: 1,
    dependencyCves: ["CVE-2024-12345"],
    promptInjectionAttemptsLast30Days: 45,
    dataExfiltrationAlertsLast30Days: 2,
    userRiskScore: 68,
    gdprStatus: "Partial",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Partial",
    policyViolationsLast30Days: 3,
    riskScore: 72,
  },
  {
    assetId: "spm-002",
    modelName: "LegalDocReviewer",
    owner: "James Chen",
    department: "Legal",
    hostingLocation: "AWS",
    modelType: "Fine-tuned model",
    thirdParty: false,
    sensitiveDataTypes: ["IP", "PII"],
    dataLineageScore: 92,
    likelihoodOfLeakage: 0.15,
    misconfigurationCount: 0,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 12,
    dataExfiltrationAlertsLast30Days: 0,
    userRiskScore: 32,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 0,
    riskScore: 28,
  },
  {
    assetId: "spm-003",
    modelName: "HealthcareAnalytics",
    owner: "Dr Emily Watson",
    department: "Healthcare",
    hostingLocation: "GCP",
    modelType: "CV model",
    thirdParty: false,
    sensitiveDataTypes: ["PHI", "PII"],
    dataLineageScore: 78,
    likelihoodOfLeakage: 0.42,
    misconfigurationCount: 5,
    highRiskVulnerabilities: 3,
    dependencyCves: ["CVE-2024-11111", "CVE-2024-22222"],
    promptInjectionAttemptsLast30Days: 8,
    dataExfiltrationAlertsLast30Days: 5,
    userRiskScore: 81,
    gdprStatus: "Non-compliant",
    euAiActStatus: "Partial",
    nistAiRmfStatus: "Non-compliant",
    policyViolationsLast30Days: 8,
    riskScore: 89,
  },
  {
    assetId: "spm-004",
    modelName: "MarketingCopilot",
    owner: "Unknown",
    department: "Marketing",
    hostingLocation: "AWS",
    modelType: "Agent",
    thirdParty: true,
    sensitiveDataTypes: ["PII"],
    dataLineageScore: 45,
    likelihoodOfLeakage: 0.67,
    misconfigurationCount: 8,
    highRiskVulnerabilities: 5,
    dependencyCves: ["CVE-2024-33333", "CVE-2024-44444", "CVE-2024-55555"],
    promptInjectionAttemptsLast30Days: 123,
    dataExfiltrationAlertsLast30Days: 12,
    userRiskScore: 94,
    gdprStatus: "Non-compliant",
    euAiActStatus: "Non-compliant",
    nistAiRmfStatus: "Non-compliant",
    policyViolationsLast30Days: 15,
    riskScore: 95,
  },
  {
    assetId: "spm-005",
    modelName: "FinancialForecast",
    owner: "Robert Williams",
    department: "Finance",
    hostingLocation: "On-premise",
    modelType: "LLM",
    thirdParty: false,
    sensitiveDataTypes: ["Financial", "IP"],
    dataLineageScore: 88,
    likelihoodOfLeakage: 0.18,
    misconfigurationCount: 1,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 5,
    dataExfiltrationAlertsLast30Days: 0,
    userRiskScore: 25,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 0,
    riskScore: 22,
  },
  {
    assetId: "spm-006",
    modelName: "HRAssistant",
    owner: "Lisa Anderson",
    department: "Human Resources",
    hostingLocation: "Azure",
    modelType: "LLM",
    thirdParty: false,
    sensitiveDataTypes: ["PII"],
    dataLineageScore: 82,
    likelihoodOfLeakage: 0.28,
    misconfigurationCount: 3,
    highRiskVulnerabilities: 2,
    dependencyCves: ["CVE-2024-66666"],
    promptInjectionAttemptsLast30Days: 34,
    dataExfiltrationAlertsLast30Days: 3,
    userRiskScore: 55,
    gdprStatus: "Partial",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Partial",
    policyViolationsLast30Days: 4,
    riskScore: 58,
  },
  {
    assetId: "spm-007",
    modelName: "CodeReviewer",
    owner: "Michael Brown",
    department: "Engineering",
    hostingLocation: "GCP",
    modelType: "Fine-tuned model",
    thirdParty: false,
    sensitiveDataTypes: ["IP"],
    dataLineageScore: 90,
    likelihoodOfLeakage: 0.12,
    misconfigurationCount: 0,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 18,
    dataExfiltrationAlertsLast30Days: 1,
    userRiskScore: 28,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 1,
    riskScore: 26,
  },
  {
    assetId: "spm-008",
    modelName: "SalesPredictor",
    owner: "Unknown",
    department: "Sales",
    hostingLocation: "AWS",
    modelType: "Agent",
    thirdParty: true,
    sensitiveDataTypes: ["Financial", "PII"],
    dataLineageScore: 52,
    likelihoodOfLeakage: 0.58,
    misconfigurationCount: 6,
    highRiskVulnerabilities: 4,
    dependencyCves: ["CVE-2024-77777", "CVE-2024-88888"],
    promptInjectionAttemptsLast30Days: 89,
    dataExfiltrationAlertsLast30Days: 7,
    userRiskScore: 87,
    gdprStatus: "Non-compliant",
    euAiActStatus: "Non-compliant",
    nistAiRmfStatus: "Partial",
    policyViolationsLast30Days: 11,
    riskScore: 84,
  },
  {
    assetId: "spm-009",
    modelName: "SupplyChainOptimiser",
    owner: "Amanda Taylor",
    department: "Operations",
    hostingLocation: "Azure",
    modelType: "LLM",
    thirdParty: false,
    sensitiveDataTypes: ["IP"],
    dataLineageScore: 86,
    likelihoodOfLeakage: 0.21,
    misconfigurationCount: 2,
    highRiskVulnerabilities: 1,
    dependencyCves: ["CVE-2024-99999"],
    promptInjectionAttemptsLast30Days: 23,
    dataExfiltrationAlertsLast30Days: 1,
    userRiskScore: 42,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 2,
    riskScore: 38,
  },
  {
    assetId: "spm-010",
    modelName: "FraudDetector",
    owner: "David Martinez",
    department: "Risk Management",
    hostingLocation: "On-premise",
    modelType: "CV model",
    thirdParty: false,
    sensitiveDataTypes: ["Financial", "PII"],
    dataLineageScore: 94,
    likelihoodOfLeakage: 0.09,
    misconfigurationCount: 0,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 3,
    dataExfiltrationAlertsLast30Days: 0,
    userRiskScore: 18,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 0,
    riskScore: 15,
  },
  {
    assetId: "spm-011",
    modelName: "ChatbotAlpha",
    owner: "Unknown",
    department: "IT",
    hostingLocation: "AWS",
    modelType: "LLM",
    thirdParty: true,
    sensitiveDataTypes: ["PII"],
    dataLineageScore: 38,
    likelihoodOfLeakage: 0.73,
    misconfigurationCount: 9,
    highRiskVulnerabilities: 6,
    dependencyCves: ["CVE-2024-10101", "CVE-2024-10102", "CVE-2024-10103"],
    promptInjectionAttemptsLast30Days: 156,
    dataExfiltrationAlertsLast30Days: 15,
    userRiskScore: 96,
    gdprStatus: "Non-compliant",
    euAiActStatus: "Non-compliant",
    nistAiRmfStatus: "Non-compliant",
    policyViolationsLast30Days: 18,
    riskScore: 97,
  },
  {
    assetId: "spm-012",
    modelName: "ProductRecommender",
    owner: "Jessica Lee",
    department: "E-commerce",
    hostingLocation: "GCP",
    modelType: "Agent",
    thirdParty: false,
    sensitiveDataTypes: ["PII"],
    dataLineageScore: 75,
    likelihoodOfLeakage: 0.32,
    misconfigurationCount: 3,
    highRiskVulnerabilities: 2,
    dependencyCves: ["CVE-2024-10104"],
    promptInjectionAttemptsLast30Days: 41,
    dataExfiltrationAlertsLast30Days: 3,
    userRiskScore: 62,
    gdprStatus: "Partial",
    euAiActStatus: "Partial",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 5,
    riskScore: 65,
  },
  {
    assetId: "spm-013",
    modelName: "ContractAnalyser",
    owner: "Thomas Green",
    department: "Procurement",
    hostingLocation: "Azure",
    modelType: "Fine-tuned model",
    thirdParty: false,
    sensitiveDataTypes: ["IP", "Financial"],
    dataLineageScore: 89,
    likelihoodOfLeakage: 0.16,
    misconfigurationCount: 1,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 14,
    dataExfiltrationAlertsLast30Days: 0,
    userRiskScore: 31,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 1,
    riskScore: 29,
  },
  {
    assetId: "spm-014",
    modelName: "SentimentAnalyser",
    owner: "Maria Rodriguez",
    department: "Customer Insights",
    hostingLocation: "AWS",
    modelType: "LLM",
    thirdParty: false,
    sensitiveDataTypes: ["PII"],
    dataLineageScore: 80,
    likelihoodOfLeakage: 0.25,
    misconfigurationCount: 2,
    highRiskVulnerabilities: 1,
    dependencyCves: ["CVE-2024-10105"],
    promptInjectionAttemptsLast30Days: 28,
    dataExfiltrationAlertsLast30Days: 2,
    userRiskScore: 48,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Partial",
    policyViolationsLast30Days: 3,
    riskScore: 52,
  },
  {
    assetId: "spm-015",
    modelName: "ImageClassifier",
    owner: "Kevin Park",
    department: "Quality Assurance",
    hostingLocation: "GCP",
    modelType: "CV model",
    thirdParty: false,
    sensitiveDataTypes: ["None"],
    dataLineageScore: 91,
    likelihoodOfLeakage: 0.08,
    misconfigurationCount: 0,
    highRiskVulnerabilities: 0,
    dependencyCves: [],
    promptInjectionAttemptsLast30Days: 2,
    dataExfiltrationAlertsLast30Days: 0,
    userRiskScore: 15,
    gdprStatus: "Compliant",
    euAiActStatus: "Compliant",
    nistAiRmfStatus: "Compliant",
    policyViolationsLast30Days: 0,
    riskScore: 12,
  },
]

// Generate Security Incidents
export const securityIncidents: SecurityIncident[] = [
  {
    incidentId: "INC-001",
    date: "2024-11-28",
    assetId: "spm-004",
    type: "Prompt injection",
    severity: "Critical",
    status: "In progress",
    mttrHours: 0,
    description: "Multiple sophisticated prompt injection attempts detected",
  },
  {
    incidentId: "INC-002",
    date: "2024-11-25",
    assetId: "spm-011",
    type: "Data exfiltration",
    severity: "Critical",
    status: "Open",
    mttrHours: 0,
    description: "Suspicious data access patterns indicating possible exfiltration",
  },
  {
    incidentId: "INC-003",
    date: "2024-11-20",
    assetId: "spm-003",
    type: "Policy violation",
    severity: "High",
    status: "Resolved",
    mttrHours: 48,
    description: "PHI data accessed without proper authorisation",
  },
  {
    incidentId: "INC-004",
    date: "2024-11-18",
    assetId: "spm-008",
    type: "Model abuse",
    severity: "High",
    status: "Resolved",
    mttrHours: 72,
    description: "Unauthorised attempts to extract training data",
  },
  {
    incidentId: "INC-005",
    date: "2024-11-15",
    assetId: "spm-001",
    type: "Prompt injection",
    severity: "Medium",
    status: "Resolved",
    mttrHours: 24,
    description: "Basic prompt injection attempt successfully blocked",
  },
  {
    incidentId: "INC-006",
    date: "2024-11-12",
    assetId: "spm-012",
    type: "Data exfiltration",
    severity: "Medium",
    status: "Resolved",
    mttrHours: 36,
    description: "Anomalous API calls detected and blocked",
  },
  {
    incidentId: "INC-007",
    date: "2024-11-08",
    assetId: "spm-006",
    type: "Policy violation",
    severity: "Low",
    status: "Resolved",
    mttrHours: 12,
    description: "Minor policy violation in data handling procedures",
  },
  {
    incidentId: "INC-008",
    date: "2024-11-05",
    assetId: "spm-014",
    type: "Prompt injection",
    severity: "Low",
    status: "Resolved",
    mttrHours: 8,
    description: "Low-sophistication prompt injection attempt detected",
  },
  {
    incidentId: "INC-009",
    date: "2024-10-30",
    assetId: "spm-004",
    type: "Data exfiltration",
    severity: "Critical",
    status: "Resolved",
    mttrHours: 96,
    description: "Confirmed data exfiltration event - containment successful",
  },
  {
    incidentId: "INC-010",
    date: "2024-10-25",
    assetId: "spm-011",
    type: "Model abuse",
    severity: "High",
    status: "Resolved",
    mttrHours: 60,
    description: "Repeated attempts to manipulate model outputs",
  },
]

// Generate AI Assets for Asset Management
export const aiAssets: AIAsset[] = [
  {
    assetId: "spm-001",
    modelName: "CustomerServiceGPT",
    version: "2.1.0",
    architecture: "Transformer",
    owner: "Sarah Mitchell",
    department: "Customer Support",
    creationDate: "2023-06-15",
    lastUpdated: "2024-11-01",
    dependencyLibraries: ["transformers", "torch", "langchain", "openai"],
    deploymentStatus: "Active",
    averageLatencyMs: 245,
    throughputQps: 120,
    modelAccuracy: 89.5,
    driftScore: 12,
    costPer1kTokens: 0.025,
    gpuHoursMonth: 450,
    cloudCostEstimateMonth: 2850,
    datasetSizeGb: 120,
    callsLast30Days: 385000,
    topUseCases: ["Customer queries", "Order status", "Product information"],
    businessUnits: ["Customer Support", "Sales"],
    mostActiveUsers: ["sarah.mitchell", "john.smith", "emma.wilson"],
  },
  {
    assetId: "spm-002",
    modelName: "LegalDocReviewer",
    version: "1.5.2",
    architecture: "Fine-tuned Transformer",
    owner: "James Chen",
    department: "Legal",
    creationDate: "2023-08-20",
    lastUpdated: "2024-10-28",
    dependencyLibraries: ["transformers", "spacy", "pdfminer", "bert"],
    deploymentStatus: "Active",
    averageLatencyMs: 1850,
    throughputQps: 15,
    modelAccuracy: 94.2,
    driftScore: 5,
    costPer1kTokens: 0.045,
    gpuHoursMonth: 280,
    cloudCostEstimateMonth: 1890,
    datasetSizeGb: 85,
    callsLast30Days: 42000,
    topUseCases: ["Contract review", "Compliance checking", "Risk assessment"],
    businessUnits: ["Legal", "Compliance"],
    mostActiveUsers: ["james.chen", "lisa.anderson", "robert.williams"],
  },
  {
    assetId: "spm-003",
    modelName: "HealthcareAnalytics",
    version: "3.0.1",
    architecture: "CNN",
    owner: "Dr Emily Watson",
    department: "Healthcare",
    creationDate: "2023-04-10",
    lastUpdated: "2024-11-15",
    dependencyLibraries: ["tensorflow", "keras", "opencv", "scikit-learn"],
    deploymentStatus: "Active",
    averageLatencyMs: 580,
    throughputQps: 45,
    modelAccuracy: 92.8,
    driftScore: 28,
    costPer1kTokens: 0.038,
    gpuHoursMonth: 720,
    cloudCostEstimateMonth: 4320,
    datasetSizeGb: 450,
    callsLast30Days: 156000,
    topUseCases: ["Medical imaging", "Diagnosis support", "Patient monitoring"],
    businessUnits: ["Healthcare", "Research"],
    mostActiveUsers: ["emily.watson", "michael.brown", "david.martinez"],
  },
  {
    assetId: "spm-004",
    modelName: "MarketingCopilot",
    version: "1.0.3",
    architecture: "RAG",
    owner: "Unknown",
    department: "Marketing",
    creationDate: "2024-09-05",
    lastUpdated: "2024-11-20",
    dependencyLibraries: ["openai", "pinecone", "langchain"],
    deploymentStatus: "Shadow",
    averageLatencyMs: 420,
    throughputQps: 25,
    modelAccuracy: 78.3,
    driftScore: 45,
    costPer1kTokens: 0.055,
    gpuHoursMonth: 180,
    cloudCostEstimateMonth: 1250,
    datasetSizeGb: 35,
    callsLast30Days: 89000,
    topUseCases: ["Content generation", "Campaign analysis", "SEO optimisation"],
    businessUnits: ["Marketing"],
    mostActiveUsers: ["unknown.user1", "unknown.user2"],
  },
  {
    assetId: "spm-005",
    modelName: "FinancialForecast",
    version: "2.3.1",
    architecture: "Transformer",
    owner: "Robert Williams",
    department: "Finance",
    creationDate: "2023-05-22",
    lastUpdated: "2024-10-15",
    dependencyLibraries: ["torch", "prophet", "pandas", "numpy"],
    deploymentStatus: "Active",
    averageLatencyMs: 320,
    throughputQps: 80,
    modelAccuracy: 91.7,
    driftScore: 8,
    costPer1kTokens: 0.032,
    gpuHoursMonth: 350,
    cloudCostEstimateMonth: 2450,
    datasetSizeGb: 95,
    callsLast30Days: 245000,
    topUseCases: ["Revenue forecasting", "Risk modelling", "Budget planning"],
    businessUnits: ["Finance", "Strategy"],
    mostActiveUsers: ["robert.williams", "amanda.taylor", "jessica.lee"],
  },
  {
    assetId: "spm-006",
    modelName: "HRAssistant",
    version: "1.8.0",
    architecture: "Agentic Orchestrator",
    owner: "Lisa Anderson",
    department: "Human Resources",
    creationDate: "2023-07-14",
    lastUpdated: "2024-11-10",
    dependencyLibraries: ["openai", "langchain", "chromadb"],
    deploymentStatus: "Active",
    averageLatencyMs: 380,
    throughputQps: 55,
    modelAccuracy: 86.4,
    driftScore: 18,
    costPer1kTokens: 0.028,
    gpuHoursMonth: 220,
    cloudCostEstimateMonth: 1680,
    datasetSizeGb: 42,
    callsLast30Days: 128000,
    topUseCases: ["Recruitment screening", "Employee queries", "Policy guidance"],
    businessUnits: ["Human Resources"],
    mostActiveUsers: ["lisa.anderson", "thomas.green", "maria.rodriguez"],
  },
  {
    assetId: "spm-007",
    modelName: "CodeReviewer",
    version: "3.2.0",
    architecture: "Fine-tuned Transformer",
    owner: "Michael Brown",
    department: "Engineering",
    creationDate: "2023-03-08",
    lastUpdated: "2024-11-18",
    dependencyLibraries: ["transformers", "tree-sitter", "codex"],
    deploymentStatus: "Active",
    averageLatencyMs: 520,
    throughputQps: 35,
    modelAccuracy: 88.9,
    driftScore: 14,
    costPer1kTokens: 0.042,
    gpuHoursMonth: 520,
    cloudCostEstimateMonth: 3250,
    datasetSizeGb: 210,
    callsLast30Days: 198000,
    topUseCases: ["Code review", "Bug detection", "Security analysis"],
    businessUnits: ["Engineering", "Security"],
    mostActiveUsers: ["michael.brown", "kevin.park", "sarah.mitchell"],
  },
  {
    assetId: "spm-008",
    modelName: "SalesPredictor",
    version: "1.2.1",
    architecture: "RAG",
    owner: "Unknown",
    department: "Sales",
    creationDate: "2024-08-12",
    lastUpdated: "2024-11-22",
    dependencyLibraries: ["openai", "weaviate", "langchain"],
    deploymentStatus: "Shadow",
    averageLatencyMs: 450,
    throughputQps: 30,
    modelAccuracy: 76.5,
    driftScore: 52,
    costPer1kTokens: 0.048,
    gpuHoursMonth: 150,
    cloudCostEstimateMonth: 1150,
    datasetSizeGb: 28,
    callsLast30Days: 67000,
    topUseCases: ["Lead scoring", "Pipeline forecasting", "Deal analysis"],
    businessUnits: ["Sales"],
    mostActiveUsers: ["unknown.user3", "unknown.user4"],
  },
  {
    assetId: "spm-009",
    modelName: "SupplyChainOptimiser",
    version: "2.0.0",
    architecture: "Transformer",
    owner: "Amanda Taylor",
    department: "Operations",
    creationDate: "2023-09-30",
    lastUpdated: "2024-10-25",
    dependencyLibraries: ["torch", "optuna", "ray", "pandas"],
    deploymentStatus: "Active",
    averageLatencyMs: 680,
    throughputQps: 20,
    modelAccuracy: 90.3,
    driftScore: 22,
    costPer1kTokens: 0.051,
    gpuHoursMonth: 420,
    cloudCostEstimateMonth: 2980,
    datasetSizeGb: 165,
    callsLast30Days: 98000,
    topUseCases: ["Inventory optimisation", "Route planning", "Demand forecasting"],
    businessUnits: ["Operations", "Logistics"],
    mostActiveUsers: ["amanda.taylor", "robert.williams", "david.martinez"],
  },
  {
    assetId: "spm-010",
    modelName: "FraudDetector",
    version: "4.1.2",
    architecture: "CNN",
    owner: "David Martinez",
    department: "Risk Management",
    creationDate: "2023-02-18",
    lastUpdated: "2024-11-05",
    dependencyLibraries: ["tensorflow", "scikit-learn", "xgboost", "pandas"],
    deploymentStatus: "Active",
    averageLatencyMs: 180,
    throughputQps: 200,
    modelAccuracy: 96.1,
    driftScore: 6,
    costPer1kTokens: 0.022,
    gpuHoursMonth: 680,
    cloudCostEstimateMonth: 4250,
    datasetSizeGb: 320,
    callsLast30Days: 542000,
    topUseCases: ["Transaction monitoring", "Anomaly detection", "Risk scoring"],
    businessUnits: ["Risk Management", "Finance"],
    mostActiveUsers: ["david.martinez", "robert.williams", "james.chen"],
  },
  {
    assetId: "spm-011",
    modelName: "ChatbotAlpha",
    version: "0.9.5",
    architecture: "RAG",
    owner: "Unknown",
    department: "IT",
    creationDate: "2024-10-01",
    lastUpdated: "2024-11-25",
    dependencyLibraries: ["openai", "faiss", "langchain"],
    deploymentStatus: "Shadow",
    averageLatencyMs: 520,
    throughputQps: 18,
    modelAccuracy: 72.8,
    driftScore: 68,
    costPer1kTokens: 0.062,
    gpuHoursMonth: 120,
    cloudCostEstimateMonth: 980,
    datasetSizeGb: 18,
    callsLast30Days: 45000,
    topUseCases: ["IT support", "Troubleshooting", "Documentation search"],
    businessUnits: ["IT"],
    mostActiveUsers: ["unknown.user5", "unknown.user6"],
  },
  {
    assetId: "spm-012",
    modelName: "ProductRecommender",
    version: "2.5.0",
    architecture: "Agentic Orchestrator",
    owner: "Jessica Lee",
    department: "E-commerce",
    creationDate: "2023-06-28",
    lastUpdated: "2024-11-12",
    dependencyLibraries: ["torch", "faiss", "transformers", "redis"],
    deploymentStatus: "Active",
    averageLatencyMs: 220,
    throughputQps: 150,
    modelAccuracy: 87.6,
    driftScore: 16,
    costPer1kTokens: 0.029,
    gpuHoursMonth: 580,
    cloudCostEstimateMonth: 3650,
    datasetSizeGb: 280,
    callsLast30Days: 478000,
    topUseCases: ["Product recommendations", "Personalisation", "Cross-selling"],
    businessUnits: ["E-commerce", "Marketing"],
    mostActiveUsers: ["jessica.lee", "maria.rodriguez", "thomas.green"],
  },
  {
    assetId: "spm-013",
    modelName: "ContractAnalyser",
    version: "1.9.0",
    architecture: "Fine-tuned Transformer",
    owner: "Thomas Green",
    department: "Procurement",
    creationDate: "2023-07-25",
    lastUpdated: "2024-10-20",
    dependencyLibraries: ["transformers", "spacy", "pdfplumber", "bert"],
    deploymentStatus: "Active",
    averageLatencyMs: 1650,
    throughputQps: 12,
    modelAccuracy: 93.4,
    driftScore: 9,
    costPer1kTokens: 0.046,
    gpuHoursMonth: 240,
    cloudCostEstimateMonth: 1720,
    datasetSizeGb: 78,
    callsLast30Days: 36000,
    topUseCases: ["Contract analysis", "Vendor assessment", "Compliance checking"],
    businessUnits: ["Procurement", "Legal"],
    mostActiveUsers: ["thomas.green", "james.chen", "lisa.anderson"],
  },
  {
    assetId: "spm-014",
    modelName: "SentimentAnalyser",
    version: "2.2.0",
    architecture: "Transformer",
    owner: "Maria Rodriguez",
    department: "Customer Insights",
    creationDate: "2023-08-05",
    lastUpdated: "2024-11-08",
    dependencyLibraries: ["transformers", "nltk", "torch", "scikit-learn"],
    deploymentStatus: "Active",
    averageLatencyMs: 290,
    throughputQps: 95,
    modelAccuracy: 85.7,
    driftScore: 20,
    costPer1kTokens: 0.031,
    gpuHoursMonth: 380,
    cloudCostEstimateMonth: 2480,
    datasetSizeGb: 145,
    callsLast30Days: 312000,
    topUseCases: ["Social media monitoring", "Review analysis", "Brand sentiment"],
    businessUnits: ["Customer Insights", "Marketing"],
    mostActiveUsers: ["maria.rodriguez", "jessica.lee", "sarah.mitchell"],
  },
  {
    assetId: "spm-015",
    modelName: "ImageClassifier",
    version: "3.1.0",
    architecture: "CNN",
    owner: "Kevin Park",
    department: "Quality Assurance",
    creationDate: "2023-05-12",
    lastUpdated: "2024-11-02",
    dependencyLibraries: ["tensorflow", "keras", "opencv", "pillow"],
    deploymentStatus: "Active",
    averageLatencyMs: 150,
    throughputQps: 180,
    modelAccuracy: 94.8,
    driftScore: 7,
    costPer1kTokens: 0.024,
    gpuHoursMonth: 520,
    cloudCostEstimateMonth: 3180,
    datasetSizeGb: 385,
    callsLast30Days: 425000,
    topUseCases: ["Defect detection", "Quality control", "Product inspection"],
    businessUnits: ["Quality Assurance", "Manufacturing"],
    mostActiveUsers: ["kevin.park", "amanda.taylor", "michael.brown"],
  },
]

// Derived metrics for AI-SPM
export const aiSpmMetrics = {
  overallRiskScore: Math.round(aiSpmAssets.reduce((sum, asset) => sum + asset.riskScore, 0) / aiSpmAssets.length),
  complianceScore: Math.round(
    (aiSpmAssets.filter(
      (a) => a.gdprStatus === "Compliant" && a.euAiActStatus === "Compliant" && a.nistAiRmfStatus === "Compliant",
    ).length /
      aiSpmAssets.length) *
      100,
  ),
  securityIncidentsYTD: securityIncidents.length,
  shadowAICount: aiSpmAssets.filter((a) => a.thirdParty || a.owner === "Unknown").length,
  estimatedFinancialRisk: 2450000,
  mttdHours: 4.2,
  mttrHours:
    securityIncidents.filter((i) => i.status === "Resolved").reduce((sum, i) => sum + i.mttrHours, 0) /
    securityIncidents.filter((i) => i.status === "Resolved").length,
  riskTrendVsLastQuarter: "down" as const,
}

// Derived metrics for Asset Management
export const assetManagementMetrics = {
  totalAssets: aiAssets.length,
  activeAssets: aiAssets.filter((a) => a.deploymentStatus === "Active").length,
  deprecatedAssets: aiAssets.filter((a) => a.deploymentStatus === "Deprecated").length,
  totalCloudCostMonth: aiAssets.reduce((sum, a) => sum + a.cloudCostEstimateMonth, 0),
  averageDriftScore: Math.round(aiAssets.reduce((sum, a) => sum + a.driftScore, 0) / aiAssets.length),
  shadowAIAssets: aiAssets.filter((a) => a.deploymentStatus === "Shadow"),
}
