import type { SaaSVendor } from './vendor-types'

// Seed data for the SaaS Vendor AI view. Illustrative but realistic — the AI
// features, sub-processors and data flows mirror how these tools actually ship
// AI today. Risk scores and compliance levels are demo values.

export const SAAS_VENDORS: SaaSVendor[] = [
  {
    id: 'openai-chatgpt',
    name: 'OpenAI — ChatGPT Enterprise',
    aiFeature: 'General-purpose chat & document analysis',
    category: 'llm-provider',
    riskScore: 38,
    discoveredVia: 'browser-extension',
    models: ['GPT-4o', 'GPT-4.1', 'o3'],
    subProcessors: ['Microsoft Azure', 'Fastly'],
    dataFlows: [
      { id: 'f1', description: 'Pasted documents & prompts', classification: 'confidential', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'CSA STAR'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'partial' },
    risks: [
      { id: 'r1', name: 'Sensitive data in prompts', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [] },
      { id: 'r2', name: 'Output overreliance', category: 'hallucination', severity: 'medium', owaspRef: 'LLM09', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Enterprise data-retention off', description: 'Zero data retention and training opt-out confirmed in contract.', status: 'applied' },
      { id: 'm2', name: 'DLP on paste', description: 'On-device redaction of PII before prompts leave the endpoint.', status: 'pending' },
    ],
    lastReviewedAt: '2026-06-02',
  },
  {
    id: 'anthropic-claude',
    name: 'Anthropic — Claude Team',
    aiFeature: 'Chat, coding & long-document reasoning',
    category: 'llm-provider',
    riskScore: 31,
    discoveredVia: 'browser-extension',
    models: ['Claude Opus 4.8', 'Claude Sonnet 4.6'],
    subProcessors: ['Amazon Web Services', 'Google Cloud'],
    dataFlows: [
      { id: 'f1', description: 'Prompts & uploaded files', classification: 'confidential', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'ISO 42001'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'covered', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'covered' },
    risks: [
      { id: 'r1', name: 'Sensitive data in prompts', category: 'data-leakage', severity: 'medium', owaspRef: 'LLM06', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'No-training default', description: 'Commercial terms exclude training on customer data by default.', status: 'applied' },
      { id: 'm2', name: 'SSO + audit log', description: 'Enforced SSO and exported audit logs to SIEM.', status: 'applied' },
    ],
    lastReviewedAt: '2026-06-10',
  },
  {
    id: 'microsoft-copilot',
    name: 'Microsoft — 365 Copilot',
    aiFeature: 'AI across Word, Excel, Teams & Outlook',
    category: 'productivity-suite',
    riskScore: 44,
    discoveredVia: 'sso',
    models: ['GPT-4o (Azure OpenAI)'],
    subProcessors: ['OpenAI', 'Azure OpenAI Service'],
    dataFlows: [
      { id: 'f1', description: 'Tenant content via Microsoft Graph', classification: 'restricted', trainsOnData: false },
      { id: 'f2', description: 'Meeting transcripts', classification: 'confidential', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'ISO 27018', 'EU Data Boundary'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'partial' },
    risks: [
      { id: 'r1', name: 'Over-broad Graph grounding', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [] },
      { id: 'r2', name: 'Oversharing via permissions', category: 'ip-exposure', severity: 'high', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Purview sensitivity labels', description: 'Sensitivity labels and DLP scope what Copilot can ground on.', status: 'pending' },
      { id: 'm2', name: 'Permission cleanup', description: 'Remediate oversharing before broad rollout.', status: 'not-applied' },
    ],
    lastReviewedAt: '2026-05-28',
  },
  {
    id: 'github-copilot',
    name: 'GitHub — Copilot',
    aiFeature: 'AI code completion & chat in the IDE',
    category: 'developer-tool',
    riskScore: 52,
    discoveredVia: 'endpoint',
    models: ['GPT-4o', 'Claude Sonnet 4.6'],
    subProcessors: ['Microsoft Azure', 'OpenAI', 'Anthropic'],
    dataFlows: [
      { id: 'f1', description: 'Source code & repo context', classification: 'restricted', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'gap', iso42001: 'partial' },
    risks: [
      { id: 'r1', name: 'Proprietary code exposure', category: 'ip-exposure', severity: 'high', mitigations: [] },
      { id: 'r2', name: 'Insecure code suggestions', category: 'compliance', severity: 'medium', owaspRef: 'LLM02', mitigations: [] },
      { id: 'r3', name: 'Secrets in context window', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Content exclusions', description: 'Exclude secret-bearing paths and private repos from context.', status: 'applied' },
      { id: 'm2', name: 'SAST on AI commits', description: 'Static analysis gate on Copilot-authored changes.', status: 'pending' },
    ],
    lastReviewedAt: '2026-06-05',
  },
  {
    id: 'google-gemini',
    name: 'Google — Gemini for Workspace',
    aiFeature: 'AI in Gmail, Docs, Sheets & Meet',
    category: 'productivity-suite',
    riskScore: 41,
    discoveredVia: 'sso',
    models: ['Gemini 2.5 Pro', 'Gemini 2.5 Flash'],
    subProcessors: ['Google Cloud'],
    dataFlows: [
      { id: 'f1', description: 'Workspace content & email', classification: 'confidential', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'ISO 27701'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'pending-renewal',
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'partial', owaspLlm: 'partial', iso42001: 'gap' },
    risks: [
      { id: 'r1', name: 'Email content grounding', category: 'data-leakage', severity: 'medium', owaspRef: 'LLM06', mitigations: [] },
      { id: 'r2', name: 'Region of processing unclear', category: 'compliance', severity: 'medium', euAiActRef: 'Art. 26', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Data-region commitment', description: 'Confirm EU processing region in renewal terms.', status: 'pending' },
    ],
    lastReviewedAt: '2026-05-19',
  },
  {
    id: 'notion-ai',
    name: 'Notion — Notion AI',
    aiFeature: 'Writing & Q&A over your workspace',
    category: 'productivity-suite',
    riskScore: 63,
    discoveredVia: 'browser-extension',
    models: ['Claude (Anthropic)', 'GPT-4o (OpenAI)'],
    subProcessors: ['Anthropic', 'OpenAI', 'Amazon Web Services'],
    dataFlows: [
      { id: 'f1', description: 'Workspace pages & databases', classification: 'confidential', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'partial', owaspLlm: 'gap', iso42001: 'gap' },
    risks: [
      { id: 'r1', name: 'Nested sub-processors', category: 'compliance', severity: 'high', euAiActRef: 'Art. 28', mitigations: [] },
      { id: 'r2', name: 'Workspace-wide grounding', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Sub-processor disclosure', description: 'Obtain full fourth-party list and notification terms.', status: 'not-applied' },
      { id: 'm2', name: 'Scope AI to non-sensitive spaces', description: 'Disable Notion AI on confidential teamspaces.', status: 'pending' },
    ],
    lastReviewedAt: '2026-04-30',
  },
  {
    id: 'salesforce-einstein',
    name: 'Salesforce — Einstein',
    aiFeature: 'AI across CRM, service & marketing',
    category: 'crm-support',
    riskScore: 47,
    discoveredVia: 'integration',
    models: ['Einstein Trust Layer', 'OpenAI (shared)'],
    subProcessors: ['Amazon Web Services', 'OpenAI'],
    dataFlows: [
      { id: 'f1', description: 'Customer records & cases', classification: 'restricted', trainsOnData: false },
    ],
    certifications: ['SOC 2 Type II', 'ISO 27001', 'ISO 27018'],
    dpa: true,
    trainingOptOut: true,
    contractStatus: 'active',
    complianceStatus: { euAiAct: 'partial', nistAiRmf: 'covered', owaspLlm: 'partial', iso42001: 'partial' },
    risks: [
      { id: 'r1', name: 'Customer PII to LLM', category: 'data-leakage', severity: 'high', owaspRef: 'LLM06', mitigations: [] },
      { id: 'r2', name: 'Prompt injection via case text', category: 'prompt-injection', severity: 'medium', owaspRef: 'LLM01', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Trust Layer masking', description: 'Einstein Trust Layer masks PII before model calls.', status: 'applied' },
      { id: 'm2', name: 'Injection filtering', description: 'Filter untrusted case content before grounding.', status: 'pending' },
    ],
    lastReviewedAt: '2026-06-01',
  },
  {
    id: 'perplexity-enterprise',
    name: 'Perplexity — Enterprise Pro',
    aiFeature: 'AI answer engine & web research',
    category: 'data-analytics',
    riskScore: 71,
    discoveredVia: 'browser-extension',
    models: ['GPT-4o', 'Claude', 'Sonar'],
    subProcessors: ['OpenAI', 'Anthropic', 'Amazon Web Services', 'Cloudflare'],
    dataFlows: [
      { id: 'f1', description: 'Research queries (may contain context)', classification: 'internal', trainsOnData: true },
    ],
    certifications: ['SOC 2 Type II'],
    dpa: false,
    trainingOptOut: true,
    contractStatus: 'expired',
    complianceStatus: { euAiAct: 'gap', nistAiRmf: 'gap', owaspLlm: 'gap', iso42001: 'gap' },
    risks: [
      { id: 'r1', name: 'No DPA in place', category: 'compliance', severity: 'critical', euAiActRef: 'Art. 26', mitigations: [] },
      { id: 'r2', name: 'Shadow adoption via personal accounts', category: 'shadow-ai', severity: 'high', mitigations: [] },
      { id: 'r3', name: 'Opaque sub-processor chain', category: 'compliance', severity: 'high', mitigations: [] },
    ],
    mitigations: [
      { id: 'm1', name: 'Block or sanction', description: 'Either sign an enterprise DPA or block at the gateway.', status: 'not-applied' },
      { id: 'm2', name: 'Migrate to sanctioned tool', description: 'Move active users onto an approved research vendor.', status: 'pending' },
    ],
    lastReviewedAt: '2026-03-22',
  },
]
