// lib/agent-discovery/data.ts
import type { DiscoveredAgent } from './types'

export const CLOUD_AGENTS: DiscoveredAgent[] = [
  // ── AWS · Bedrock AgentCore ──
  { id: 'aws-1', name: 'Automated Control Auditor', cloud: 'aws', registry: 'Bedrock AgentCore', owner: 'Security Engineering', protocol: 'mcp', purpose: 'Continuously audits IAM and config drift against SOC2 controls.', approvalState: 'approved', dataClassification: 'internal', regulatoryScope: ['SOC2'], region: 'us-east-1', residencyOk: true, manifestComplete: true },
  { id: 'aws-2', name: 'Incident Response Triage', cloud: 'aws', registry: 'Bedrock AgentCore', owner: 'SecOps', protocol: 'a2a', purpose: 'Triages GuardDuty findings and drafts response runbooks.', approvalState: 'approved', dataClassification: 'confidential', regulatoryScope: ['SOC2'], region: 'us-east-1', residencyOk: true, manifestComplete: true },
  { id: 'aws-3', name: 'Customer Refund Adjudicator', cloud: 'aws', registry: 'Bedrock AgentCore', owner: 'unknown', protocol: 'none', purpose: 'Approves customer refunds from support tickets.', approvalState: 'unregistered', dataClassification: 'restricted', regulatoryScope: ['PCI-DSS'], region: 'us-west-2', residencyOk: true, manifestComplete: false },
  { id: 'aws-4', name: 'Marketing Copy Generator', cloud: 'aws', registry: 'Bedrock AgentCore', owner: 'Growth', protocol: 'mcp', purpose: 'Generates campaign copy and subject lines.', approvalState: 'pending', dataClassification: 'public', regulatoryScope: [], region: 'us-east-1', residencyOk: true, manifestComplete: true },
  { id: 'aws-5', name: 'Patient Intake Summarizer', cloud: 'aws', registry: 'Bedrock AgentCore', owner: 'unknown', protocol: 'none', purpose: 'Summarizes patient intake forms for clinicians.', approvalState: 'unregistered', dataClassification: 'restricted', regulatoryScope: ['HIPAA'], region: 'us-east-1', residencyOk: false, manifestComplete: false },

  // ── Azure · AI Foundry Hub ──
  { id: 'azure-1', name: 'Policy Exception & Risk Assessment', cloud: 'azure', registry: 'AI Foundry Hub', owner: 'GRC', protocol: 'mcp', purpose: 'Evaluates policy exception requests and scores residual risk.', approvalState: 'approved', dataClassification: 'confidential', regulatoryScope: ['ISO27001'], region: 'westeurope', residencyOk: true, manifestComplete: true },
  { id: 'azure-2', name: 'Contract Clause Extractor', cloud: 'azure', registry: 'AI Foundry Hub', owner: 'Legal', protocol: 'a2a', purpose: 'Extracts obligations and liabilities from contracts.', approvalState: 'approved', dataClassification: 'confidential', regulatoryScope: ['GDPR'], region: 'westeurope', residencyOk: true, manifestComplete: true },
  { id: 'azure-3', name: 'HR Candidate Ranker', cloud: 'azure', registry: 'AI Foundry Hub', owner: 'unknown', protocol: 'none', purpose: 'Ranks job candidates from CVs and interview notes.', approvalState: 'unregistered', dataClassification: 'restricted', regulatoryScope: ['GDPR', 'EU-AI-ACT'], region: 'eastus', residencyOk: false, manifestComplete: false },
  { id: 'azure-4', name: 'Finance Variance Explainer', cloud: 'azure', registry: 'AI Foundry Hub', owner: 'Finance', protocol: 'mcp', purpose: 'Explains budget variances in management reports.', approvalState: 'pending', dataClassification: 'internal', regulatoryScope: ['SOX'], region: 'westeurope', residencyOk: true, manifestComplete: true },
  { id: 'azure-5', name: 'Support Macro Suggester', cloud: 'azure', registry: 'AI Foundry Hub', owner: 'Support', protocol: 'mcp', purpose: 'Suggests reply macros to support agents.', approvalState: 'approved', dataClassification: 'internal', regulatoryScope: [], region: 'westeurope', residencyOk: true, manifestComplete: false },

  // ── GCP · Knowledge Catalog ──
  { id: 'gcp-1', name: 'Data Lineage Mapper', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'Data Platform', protocol: 'mcp', purpose: 'Maps PII lineage across BigQuery datasets.', approvalState: 'approved', dataClassification: 'confidential', regulatoryScope: ['GDPR'], region: 'europe-west4', residencyOk: true, manifestComplete: true },
  { id: 'gcp-2', name: 'Sales Forecast Assistant', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'Revenue Ops', protocol: 'a2a', purpose: 'Forecasts pipeline from CRM signals.', approvalState: 'approved', dataClassification: 'internal', regulatoryScope: [], region: 'us-central1', residencyOk: true, manifestComplete: true },
  { id: 'gcp-3', name: 'Loan Pre-Approval Scorer', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'unknown', protocol: 'none', purpose: 'Pre-scores loan applications before underwriting.', approvalState: 'unregistered', dataClassification: 'restricted', regulatoryScope: ['EU-AI-ACT', 'GDPR'], region: 'us-central1', residencyOk: false, manifestComplete: false },
  { id: 'gcp-4', name: 'Knowledge Base Answerer', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'IT', protocol: 'mcp', purpose: 'Answers internal IT questions from the wiki.', approvalState: 'pending', dataClassification: 'internal', regulatoryScope: [], region: 'europe-west4', residencyOk: true, manifestComplete: true },
  { id: 'gcp-5', name: 'Procurement Vendor Vetter', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'Procurement', protocol: 'mcp', purpose: 'Vets new vendors against risk and sanctions lists.', approvalState: 'approved', dataClassification: 'confidential', regulatoryScope: ['ISO27001'], region: 'europe-west4', residencyOk: true, manifestComplete: true },
  { id: 'gcp-6', name: 'Ad Spend Optimizer', cloud: 'gcp', registry: 'Knowledge Catalog', owner: 'unknown', protocol: 'none', purpose: 'Reallocates ad budget across channels autonomously.', approvalState: 'unregistered', dataClassification: 'internal', regulatoryScope: [], region: 'us-central1', residencyOk: true, manifestComplete: false },
]
